import { appSchema, tableSchema } from "@nozbe/watermelondb";

export const databaseSchema = appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: "shops",
      columns: [
        { name: "name", type: "string" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "categories",
      columns: [
        { name: "name", type: "string" },
        { name: "shop_id", type: "string", isIndexed: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "types",
      columns: [
        { name: "name", type: "string" },
        { name: "category_id", type: "string", isIndexed: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "vendors",
      columns: [
        { name: "name", type: "string" },
        { name: "phone_number", type: "string" },
        { name: "credit_amount", type: "number" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "tax_types",
      columns: [
        { name: "name", type: "string" },
        { name: "code", type: "string" },
        { name: "rate", type: "number" },
        { name: "active", type: "boolean" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "products",
      columns: [
        { name: "barcode", type: "string", isOptional: true },
        { name: "name", type: "string" },
        { name: "shop_id", type: "string", isIndexed: true },
        { name: "category_id", type: "string", isIndexed: true },
        { name: "type_id", type: "string", isIndexed: true, isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
        { name: "current_stock", type: "number" },
        { name: "total_purchased", type: "number" },
        { name: "total_sold", type: "number" },
        { name: "current_batch_id", type: "string", isOptional: true },
        { name: "batch_count", type: "number", isOptional: true },
        { name: "unit", type: "string" },
        { name: "active", type: "boolean" },
      ],
    }),
    tableSchema({
      name: "drafts",
      columns: [
        { name: "name", type: "string" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "draft_items",
      columns: [
        { name: "draft_id", type: "string", isIndexed: true },
        { name: "product_id", type: "string", isIndexed: true },
        { name: "quantity", type: "number" },
        { name: "purchase_unit", type: "string" },
        { name: "units_per_pack", type: "number" },
        { name: "expiry", type: "string", isOptional: true },
        { name: "unit_cost", type: "number" },
        { name: "unit_selling_price", type: "number" },
        { name: "profit_amount", type: "number" },
        { name: "profit_scope", type: "string" },
        { name: "price", type: "number" },
        { name: "tax_type_id", type: "string", isIndexed: true, isOptional: true },
        {name: "tax_amount", type: "number", isOptional: true},
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "batches",
      columns: [
        { name: "vendor_id", type: "string", isIndexed: true, isOptional: true },
        { name: "payment_method", type: "string" },
        { name: "total_amount", type: "number" },
        { name: "amount_paid", type: "number" },
        { name: "balance", type: "number" },
        { name: "vendor", type: "string", isIndexed: true, isOptional: true },
        { name: "status", type: "string" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "batch_payments",
      columns: [
        { name: "batch_id", type: "string", isIndexed: true },
        { name: "payment_method", type: "string" },
        { name: "amount", type: "number" },
        { name: "reference", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "batch_items",
      columns: [
        { name: "batch_id", type: "string", isIndexed: true },
        { name: "product_id", type: "string", isIndexed: true },
        { name: "quantity", type: "number" },
        { name: "purchase_unit", type: "string" },
        { name: "units_per_pack", type: "number", isOptional: true },
        { name: "expiry", type: "string", isOptional: true },
        { name: "unit_cost", type: "number" },
        { name: "unit_selling_price", type: "number" },
        { name: "profit_amount", type: "number" },
        { name: "profit_scope", type: "string" },
        { name: "price", type: "number" },
        { name: "tax_type_id", type: "string", isIndexed: true, isOptional: true },
        {name: "tax_amount", type: "number", isOptional: true},
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "sales",
      columns: [
        { name: "receipt_number", type: "string", isIndexed: true },
        { name: "customer_name_snapshot", type: "string", isOptional: true },
        { name: "creditor_id", type: "string", isIndexed: true, isOptional: true },
        { name: "subtotal", type: "number" },
        { name: "discount", type: "number" },
        { name: "tax", type: "number" },
        { name: "total", type: "number" },
        { name: "amount_paid", type: "number" },
        { name: "balance", type: "number" },
        { name: "cost_total", type: "number" },
        { name: "gross_profit", type: "number" },
        { name: "status", type: "string" },
        { name: "reversal_of_sale_id", type: "string", isIndexed: true, isOptional: true },
        { name: "reversal_reason", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "completed_at", type: "number", isOptional: true },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "sale_payments",
      columns: [
        { name: "sale_id", type: "string", isIndexed: true },
        { name: "payment_method", type: "string" },
        { name: "amount", type: "number" },
        { name: "reference", type: "string", isOptional: true },
        { name: "status", type: "string" },
        { name: "created_at", type: "number" },
        { name: "reversed_at", type: "number", isOptional: true },
      ],
    }),
    tableSchema({
      name: "sales_items",
      columns: [
        { name: "sale_id", type: "string", isIndexed: true },
        { name: "product_id", type: "string", isIndexed: true },
        { name: "batch_id", type: "string", isIndexed: true },
        { name: "batch_item_id", type: "string", isIndexed: true },
        { name: "product_name_snapshot", type: "string" },
        { name: "product_barcode_snapshot", type: "string", isOptional: true },
        { name: "quantity", type: "number" },
        { name: "unit_selling_price", type: "number" },
        { name: "line_total", type: "number" },
        { name: "unit_cost", type: "number" },
        { name: "line_cost", type: "number" },
        { name: "gross_profit", type: "number" },
        { name: "stock_movement_id", type: "string", isIndexed: true, isOptional: true },
        { name: "created_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "creditors",
      columns: [
        { name: "name", type: "string" },
        { name: "phone_number", type: "string" },
        { name: "location", type: "string" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "creditor_sales",
      columns: [
        { name: "creditor_id", type: "string", isIndexed: true },
        { name: "sale_id", type: "string", isIndexed: true },
        { name: "original_amount", type: "number" },
        { name: "amount_paid", type: "number" },
        { name: "balance", type: "number" },
        { name: "status", type: "string" },
        { name: "created_at", type: "number" },
        { name: "settled_at", type: "number", isOptional: true },
      ],
    }),
    tableSchema({
      name: "creditor_repayments",
      columns: [
        { name: "creditor_sale_id", type: "string", isIndexed: true },
        { name: "sale_payment_id", type: "string", isIndexed: true, isOptional: true },
        { name: "payment_method", type: "string" },
        { name: "amount", type: "number" },
        { name: "reference", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "vendor_credits",
      columns: [
        { name: "vendor_id", type: "string", isIndexed: true },
        { name: "batch_id", type: "string", isIndexed: true },
        { name: "original_amount", type: "number" },
        { name: "amount_paid", type: "number" },
        { name: "balance", type: "number" },
        { name: "status", type: "string" },
        { name: "created_at", type: "number" },
        { name: "settled_at", type: "number", isOptional: true },
      ],
    }),
    tableSchema({
      name: "vendor_credit_payments",
      columns: [
        { name: "vendor_credit_id", type: "string", isIndexed: true },
        { name: "batch_payment_id", type: "string", isIndexed: true, isOptional: true },
        { name: "payment_method", type: "string" },
        { name: "amount", type: "number" },
        { name: "reference", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "stock_movements",
      columns: [
        { name: "product_id", type: "string", isIndexed: true },
        { name: "quantity_delta", type: "number" },
        { name: "reason_type", type: "string" },
        { name: "reason_id", type: "string", isIndexed: true },
        { name: "unit_cost", type: "number" },
        { name: "unit_selling_price", type: "number" },
        { name: "created_at", type: "number" },
      ],
    }),
  ],
});
